### ISSUE TITLE
The link doesn't function

### ISSUE THREAD

**Issue by ZOLDIK0** [MrAnssaien/fortnite_offline_installer#1]
the links keeps looping on the 'recaptcha' check when trying to download from  https://nssys.co/fortnite/download

**Comment by MrAnssaien** [comment]
> 
> 
> the links keeps looping on the 'recaptcha' check when trying to download from https://nssys.co/fortnite/download

It's working perfectly. I've just tried on on Firefox 76, using Internet Download Manager.
